### PR TITLE
added get_KSN_omnipath function

### PR DESCRIPTION
**Pull request by adugourd**
Yo check mah stuff pliz

### CODE REVIEW

**Comment by dbdimitrov** [comment]
nice stuff

**Comment by PauBadiaM** [comment]
nono, it brok

**Comment by adugourd** [comment]
> 

image

**Review by deeenes — COMMENTED** [review]
With some `tidyverse` could look like this :P

I only don't understand, why the MOR should be -1 in case of duplicates? Is it because those are definitely also dephosphorylations?

```
#' Kinase-substrate network from OmniPath
#'
#' @param ... Passed to ``OmnipathR::import_omnipath_enzsub``.
#'
#' @importFrom magrittr %>% %T>%
#' @importFrom rlang !!!
#' @importFrom OmnipathR import_omnipath_enzsub omnipath_msg
#' @importFrom dplyr filter mutate select group_by ungroup distinct
#' @export
ksn_omnipath <- function(...) {

    # NSE vs. R CMD check workaround
    modification <- substrate_genesymbol <- residue_type <- residue_offset <-
    enzyme_genesymbol <- target <- mor <- comb <- NULL

    list(...) %>%
    OmnipathR::import_omnipath_enzsub(!!!.) %>%
    filter(modification %in% c("phosphorylation","dephosphorylation")) %>%
    mutate(
        target = sprintf(
            '%s_%s%i',
            substrate_genesymbol,
            residue_type,
            residue_offset
        ),
        mor = ifelse(modification == 'phosphorylation', 1L, -1L)
    ) %>%
    select(source = enzyme_genesymbol, target, mor) %>%
    distinct %>%
    mutate(comb = sprintf('%s_%s', source, target)) %>%
    group_by(comb) %>%
    # how this makes sense? - Denes
    mutate(mor = ifelse(n() > 1L, -1L, mor)) %>%
    ungroup %>%
    distinct %>%
    select(-comb) %T>%
    {OmnipathR::omnipath_msg(
        'success',
        'Collected %i enzyme substrate interactions.',
        nrow(.)
    )}

}
```

**Comment by deeenes** [comment]
After a very short look, these all seem to be phosphatases, so MOR -1 is correct. Slightly simpler implementation, plus I checked that `mor = min(mor)` gives the same output, and more justifiable:

```
#' Kinase-substrate network from OmniPath
#'
#' @param ... Passed to ``OmnipathR::import_omnipath_enzsub``.
#'
#' @importFrom magrittr %>% %T>%
#' @importFrom rlang !!!
#' @importFrom OmnipathR import_omnipath_enzsub omnipath_msg
#' @importFrom dplyr filter mutate select group_by ungroup distinct
#' @importFrom dplyr summarize_all first
#' @export
ksn_omnipath <- function(...) {

    # NSE vs. R CMD check workaround
    modification <- substrate_genesymbol <- residue_type <- residue_offset <-
    enzyme_genesymbol <- target <- mor <- comb <- NULL

    list(...) %>%
    OmnipathR::import_omnipath_enzsub(!!!.) %>%
    filter(modification %in% c('phosphorylation', 'dephosphorylation')) %>%
    mutate(
        target = sprintf(
            '%s_%s%i',
            substrate_genesymbol,
            residue_type,
            residue_offset
        ),
        mor = (modification == 'phosphorylation') * 2L - 1L
    ) %>%
    select(source = enzyme_genesymbol, target, mor) %>%
    distinct %>%
    group_by(source, target) %>%
    mutate(mor = min(mor)) %>%
    summarize_all(first) %>%
    ungroup %T>%
    {OmnipathR::omnipath_msg(
        'success',
        '%i enzyme-PTM interactions after preprocessing.',
        nrow(.)
    )}

}
```

**Comment by adugourd** [comment]
LGTM

**Comment by PauBadiaM** [comment]
Looks good! @adugourd could you change your function to this and push it?

**Comment by deeenes** [comment]
Btw the checks fail because of OmnipathR, in master I fixed it already

**Pull request merged**
